openapi: 3.0.0
info:
  title: Wolfram|Alpha Full Results API (Subset)
  description: A subset of the Wolfram|Alpha Full Results API for querying computational knowledge, based on the provided JSON response structure.
  version: 2.0.0
servers:
  - url: https://api.wolframalpha.com/v2
    description: Wolfram|Alpha API Server
paths:
  /query:
    get:
      summary: Query Wolfram|Alpha for computational results
      description: Submits a free-form query to Wolfram|Alpha and returns computational results in JSON format.
      parameters:
        - name: appid
          in: query
          description: The application ID for authentication
          required: true
          schema:
            type: string
        - name: input
          in: query
          description: The query string to be processed (URL-encoded)
          required: true
          schema:
            type: string
        - name: output
          in: query
          description: The desired format for the full result
          required: false
          schema:
            type: string
            enum: [json]
            default: json
      responses:
        '200':
          description: Successful response with computational results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResult'
        '400':
          description: Bad request due to invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    QueryResult:
      type: object
      properties:
        queryresult:
          type: object
          properties:
            success:
              type: boolean
              description: Indicates if the query was successfully processed
            error:
              type: boolean
              description: Indicates if a processing error occurred
            numpods:
              type: integer
              description: Number of pods in the response
            datatypes:
              type: string
              description: Categories of data represented in the results
            timedout:
              type: string
              description: List of scanners that timed out (comma-separated)
            timedoutpods:
              type: string
              description: List of pods that timed out (comma-separated)
            timing:
              type: number
              description: Wall-clock time in seconds to generate the output
            parsetiming:
              type: number
              description: Time in seconds for the parsing phase
            parsetimedout:
              type: boolean
              description: Whether the parsing stage timed out
            recalculate:
              type: string
              description: URL to recalculate the query for more pods
            id:
              type: string
              description: Unique identifier for the query result
            host:
              type: string
              description: Host server URL
            server:
              type: string
              description: Server identifier
            related:
              type: string
              description: URL for related queries
            version:
              type: string
              description: API version used
            inputstring:
              type: string
              description: Original input string submitted
            pods:
              type: array
              items:
                $ref: '#/components/schemas/Pod'
            assumptions:
              $ref: '#/components/schemas/Assumptions'
    Pod:
      type: object
      properties:
        title:
          type: string
          description: Title of the pod (e.g., "Result")
        scanner:
          type: string
          description: Name of the scanner that produced the pod
        id:
          type: string
          description: Unique identifier for the pod
        position:
          type: integer
          description: Intended display position of the pod
        error:
          type: boolean
          description: Indicates if an error occurred in this pod
        numsubpods:
          type: integer
          description: Number of subpods in the pod
        primary:
          type: boolean
          description: Indicates if this is the primary pod (optional)
        subpods:
          type: array
          items:
            $ref: '#/components/schemas/Subpod'
        expressiontypes:
          $ref: '#/components/schemas/ExpressionTypes'
    Subpod:
      type: object
      properties:
        title:
          type: string
          description: Title of the subpod (often empty)
        img:
          $ref: '#/components/schemas/Image'
        plaintext:
          type: string
          description: Textual representation of the subpod content
    Image:
      type: object
      properties:
        src:
          type: string
          description: URL of the image
        alt:
          type: string
          description: Alternate text for the image
        title:
          type: string
          description: Title of the image
        width:
          type: integer
          description: Width of the image in pixels
        height:
          type: integer
          description: Height of the image in pixels
        type:
          type: string
          description: Type of the image content
        themes:
          type: string
          description: Comma-separated list of applicable themes
        colorinvertable:
          type: boolean
          description: Whether the image can be color-inverted
        contenttype:
          type: string
          description: MIME type of the image
    ExpressionTypes:
      type: object
      properties:
        name:
          type: string
          description: Name of the expression type
    Assumptions:
      type: object
      properties:
        type:
          type: string
          description: Type of assumption made
        template:
          type: string
          description: Template for the assumption message
        count:
          type: integer
          description: Number of assumption values
        values:
          type: array
          items:
            $ref: '#/components/schemas/AssumptionValue'
    AssumptionValue:
      type: object
      properties:
        name:
          type: string
          description: Name of the assumption value
        desc:
          type: string
          description: Description of the assumption value
        input:
          type: string
          description: Input string to use this assumption
    ErrorResponse:
      type: object
      properties:
        queryresult:
          type: object
          properties:
            success:
              type: boolean
            error:
              type: boolean
            numpods:
              type: integer
            datatypes:
              type: string
            timedout:
              type: string
            timedoutpods:
              type: string
            timing:
              type: number
            parsetiming:
              type: number
            parsetimedout:
              type: boolean
            recalculate:
              type: string
            id:
              type: string
            host:
              type: string
            server:
              type: string
            related:
              type: string
            version:
              type: string
              properties:
                code:
                  type: integer
                  description: Error code
                msg:
                  type: string
                  description: Error message

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: appid
